//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenzaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentari
    {
        public int id { get; set; }
        public string komentarContent { get; set; }
        public int idMenza { get; set; }
        public int idKorisnik { get; set; }
        public System.DateTime vrijemeDatum { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Menza Menza { get; set; }
    }
}
